# Use root/example as user/password credentials
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11.6-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672" # Rabbitmq suhtlusport
      - "15672:15672" # Rabbitmq UI adminliidese port
    hostname: cumuservice_rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  cumudb:
    image: mongo
    ports:
      - ${MONGO__PORT}:${MONGO__PORT}
    restart: "no"
    volumes:
      - cumu-data:/data/db #/host/path:/container/path. Devis on see WSL peal
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  cumudb-express:
    image: mongo-express
    depends_on:
      - cumudb
    restart: "unless-stopped"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@cumudb:${MONGO__PORT}
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_VOLUMES: ${MINIO_VOLUMES}
    command: server --console-address ":9090" ${MINIO_VOLUMES}
volumes:
  cumu-data:
  rabbitmq-data:
  minio-data: